api-version: 1.16
name: Nosto-Sheepwars
version: 0.0.1
author: djredstone
main: fr.djredstone.sheepwars.Main
commands:
  sheepwars:
    description: Default command
  sw:
    description: Same thing