api-version: 1.16
name: Nosto-Survival
version: 0.0.1
authors: [djredstone, itsRed_v2]
main: fr.nostoS.Main
commands:
  afk:
    description: Permet de se mettre AFK ou non
    usage: /afk
  sethome:
    decription: Permet de faire des homes
  home:
    description: Permet de se tp aux homes
  delhome:
    description: Permet de retirer des homes
  claim:
    description: Permet de claim des chunk
  unclaim:
    description: Permet d'unclaim des chunk