main: fr.nostoNC.Main
api-version: 1.18
name: Nosto-Nightclub
version: 0.0.1
authors: [djredstone, itsRed_v2]
commands:
  nightclub:
    description: Nightclub Command
  getfood:
    description: Permet de se give les différentes boissons et nourritures du club
    usage: /getdrink <nom>
    permission: nosto.nightclub.getfood