main: fr.nostoNC.Main
api-version: 1.16
name: Nosto-Nightclub
version: 0.0.1
authors: [djredstone, itsRed_v2]
commands:
  nightclub:
    description: Nightclub Command
  getdrink:
    description: Permet de se give les différentes boissons du club
    usage: /getdrink <nom>
    permission: nosto.nightclub.getdrink