api-version: 1.17
name: Plugin-Custom-Nosto
version: 0.0.1
authors: [djredstone, itsRed_v2]
main: fr.nosto.Main
commands:
  annonce:
    description: "Permet de créer des annonces"
    usage: /annonce <message>
    permission: nosto.admin.annonce
  cleartchat:
    description: "Permet de clear le tchat"
    usage: /cleartchat
    permission: nosto.admin.cleartchat
    aliases: ct
  event:
    description: "Permet de creer des events et de les rejoindre"
    usage: "/event\n
    /event add <type>\n
    /event stop"
  feed:
    description: "Permet de régénérer sa barre de nourriture"
    usage: /feed
    permission: nosto.feed
  fly:
    description: "Permet de voler"
    usage: /fly ou /fly <joueur>
    permission: nosto.fly
  freeze:
    description: "Permet de freeze un joueur"
    usage: /freeze <joueur>
    permission: nosto.admin.freeze
  heal:
    description: "Permet de régénérer sa barre de nourriture et de vie"
    usage: /heal
    permission: nosto.heal
  lobby:
    description: "Permet de revenir au lobby principal"
    usage: /lobby
    aliases: hub
  me:
    description: "Permet de simuler une action"
    usage: /me <action>
  menu:
    description: "Permet d'afficher le menu Principal"
    usage: /menu
  msg:
    description: "Permet d'envoyer des message privées à d'autres joueurs"
    usage: /msg <joueur> ou /msg <joueur> <message>
  nosto:
    description: "Permet de faire pas mal de chose (commande admin)"
    usage: /nosto normaljoin ou /nosto reloadconfig ou /nosto openmenu <nom du menu>
    permission: nosto.admin.commandnosto
  sit:
    description: "Permet de s'assoir"
    usage: /sit
  spawn:
    description: "Permet de se TP au spawn du monde"
    usage: /spawn
  speed:
    description: "Permet de modifier la vitesse de vol ou de marche:\n
    - si le joueur est au sol, la vitesse de marche sera modifiée.\n
    - si il est en vol, la vitesse de vol sera modifiée."
    usage: /speed <vitesse>
    permission: nosto.speed
  staffChat:
    description: Chat privé pour le staff
    usage: /staffchat <message>
    permission: nosto.admin.chat
    aliases: sc
  vanish:
    description: Permet de se rendre invisible
    permission: nosto.admin.vanish