api-version: 1.16
name: Plugin-Custom-Nosto
version: 0.0.1
authors: [djredstone, itsRed_v2]
main: fr.nosto.Main
commands:
  annonce:
    description: Commande annonce
    permission: nosto.admin.annonce
  fly:
    description: Permet de voler
    permission: nosto.fly
  speed:
    description: Permet de modifier la vitesse de vol et de marche
    permission: nosto.speed
  afk:
    description: Juste AFK
  staffChat:
    description: Chat pour le staff
    permission: nosto.admin.chat
  sc:
    description: Chat pour le staff
    permission: nosto.admin.chat
  spawn:
    description: Permet de se TP au spawn du monde
  feed:
    description: Permet de manger
    permission: nosto.feed
  heal:
    description: Permet de vivre
    permission: nosto.heal
  msg:
    description: Permet d'envoyer des message privees
  nosto:
    description: Reload Custom
    permission: nosto.admin.reload
  freeze:
    description: Permet de freeze un joueur
    permission: nosto.admin.freeze
  sethome:
    decription: Permet de faire des homes
  home:
    description: Permet de se tp aux homes
  delhome:
    description: Permet de retirer des homes
  claim:
    description: Permet de claim des chunk
  unclaim:
    description: Permet d'unclaim des chunk
  clearTchat:
    description: Permet de clear le tchat
    permission: nosto.admin.cleartchat
  ct:
    description: Permet de clear le tchat
    permission: nosto.admin.cleartchat
  sit:
    description: Permet de s'assoir
  vanish:
    description: Permet de se rendre invisible
    permission: nosto.admin.vanish
  event:
    description : Permet de creer des events
    permission: nosto.admin.event
  menu:
    description: Menu Principal